### PR TITLE
Page with greeting header

### PR DESCRIPTION
**Pull request by hansenteguh**
Finish the file

### CODE REVIEW

**Review by albertoam2 — COMMENTED** [review]
This is good but could you add a message, "we are ready to serve you" and make the color red

**Comment by hansenteguh** [comment]
Got it!

**Review by hansenteguh — COMMENTED** [review]
Got it!

**Review by albertoam2 — CHANGES_REQUESTED** [review]
Please make the necessary changes.

**Review by albertoam2 — APPROVED** [review]

**Pull request merged**
